config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-white-spoonbill.sh
        container: qc.acc_cranky-amaranth-antelope
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-salmon-starfish.sh
        container: qc.doc_gamy-magnolia-barb
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-thistle-blue.sh
        container: qc.doc_squeaky-purple-grasshopper
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-wheat-cuttlefish.sh
        container: qc.doc_ugly-rust-woodlouse
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-taupe-lizard.sh
        container: qc.doc_slaphappy-cinnamon-budgerigar
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-white-mongoose.sh
        container: qc.lic_sloppy-gold-affenpinscher
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ivory-beaver.sh
        container: qc.met_flaky-puce-gorilla
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cinnamon-malamute.sh
        container: qc.sec_beady-ultramarine-hippopotamus
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-plum-dogfish.sh
        container: qc.sty_breezy-beige-saola
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ecru-discus.sh
        container: qc.sty_goopy-smalt-echidna
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bronze-dalmatian.sh
        container: qc.sty_craggy-cream-barracuda
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-maroon-penguin.sh
        container: qc.uni_seedy-ultramarine-mouse
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-myrtle-frigatebird.sh
        container: qc.ver_stealthy-aquamarine-rat
timeout: 5400
