config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-periwinkle-whippet.sh
        container: qc.acc_stealthy-seashell-kiwi
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-teal-avocet.sh
        container: qc.doc_craggy-charcoal-dollar
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-vermilion-cattle.sh
        container: qc.doc_pokey-crimson-tuatara
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-lemon-worm.sh
        container: qc.doc_woozy-saffron-gharial
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-indigo-setter.sh
        container: qc.doc_homely-carmine-moth
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.ready-rose-moorhen.sh
        container: qc.doc_crabby-corn-beaver
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-asparagus-mau.sh
        container: qc.lic_randy-peach-foxhound
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-yellow-gibbon.sh
        container: qc.met_jumpy-charcoal-lion
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cornflower-tamarin.sh
        container: qc.sec_snoopy-orange-gopher
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-puce-bracke.sh
        container: qc.sec_slaphappy-dandelion-bonobo
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-malachite-mau.sh
        container: qc.sty_freaky-orange-chicken
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-russet-squid.sh
        container: qc.sty_surly-emerald-dog
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-pink-devil.sh
        container: qc.sty_leaky-alizarin-lizard
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-brown-corgi.sh
        container: qc.sty_boozy-silver-clam
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-rust-quetzal.sh
        container: qc.uni_craggy-scarlet-leopard
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-razzmatazz-beetle.sh
        container: qc.ver_wimpy-tomato-hamster
timeout: 5400
