config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-mauve-drever.sh
        container: qc.acc_cozy-peach-tetra
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-bronze-wallaby.sh
        container: qc.doc_nippy-ultramarine-kangaroo
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-peach-drever.sh
        container: qc.doc_woozy-red-horse
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-puce-angora.sh
        container: qc.doc_woolly-tan-squid
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cobalt-sponge.sh
        container: qc.doc_droopy-amaranth-dachshund
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-white-bee.sh
        container: qc.lic_craggy-ruby-eleuth
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-alizarin-hamster.sh
        container: qc.met_clammy-yellow-civet
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-grey-alligator.sh
        container: qc.sec_gloppy-burgundy-bonobo
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-carmine-caracal.sh
        container: qc.sty_randy-burgundy-donkey
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-vermilion-salamander.sh
        container: qc.sty_cheeky-cinnabar-beaver
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-russet-newfoundland.sh
        container: qc.sty_slimy-tan-wombat
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chocolate-falcon.sh
        container: qc.uni_woozy-sangria-vulture
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-tomato-paradise.sh
        container: qc.ver_wiggy-sangria-vole
timeout: 5400
