config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: sqa
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-puce-retriever.sh
        container: qc.acc_squeaky-goldenrod-quokka
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-buff-dhole.sh
        container: qc.doc_blurry-alizarin-ragdoll
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-silver-rattlesnake.sh
        container: qc.doc_freaky-maroon-mouse
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-corn-tuatara.sh
        container: qc.lic_flimsy-peach-newt
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cinnabar-cougar.sh
        container: qc.ver_homely-razzmatazz-moose
timeout: 5400
