config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-amber-antelope.sh
        container: qc.acc_sloppy-platinum-labradoodle
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-copper-tamarin.sh
        container: qc.doc_breezy-pear-macaw
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-teal-russel.sh
        container: qc.doc_wimpy-vermilion-reindeer
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-khaki-maltese.sh
        container: qc.doc_skanky-periwinkle-chinchilla
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-auburn-uguisu.sh
        container: qc.doc_pasty-maroon-crab
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cornflower-dhole.sh
        container: qc.lic_shaggy-gold-chicken
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-pink-penguin.sh
        container: qc.met_messy-apricot-wombat
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-white-toucan.sh
        container: qc.sec_skimpy-brown-seahorse
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lavender-hippopotamus.sh
        container: qc.sty_muggy-brass-tiger
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-champagne-tarsier.sh
        container: qc.sty_hasty-crimson-akita
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-vermilion-oyster.sh
        container: qc.sty_chewy-bistre-gorilla
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-viridian-orangutan.sh
        container: qc.uni_snippy-chocolate-discus
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-goldenrod-harrier.sh
        container: qc.ver_stinky-lime-dogfish
timeout: 5400
