config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-black-birman.sh
        container: qc.acc_whiny-turquoise-moth
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-turquoise-balinese.sh
        container: qc.doc_homely-cardinal-zorse
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-carmine-fowl.sh
        container: qc.doc_crabby-periwinkle-chinook
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-vermilion-molly.sh
        container: qc.doc_droopy-charcoal-robin
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cinnamon-nightingale.sh
        container: qc.doc_homey-platinum-maltese
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-myrtle-hare.sh
        container: qc.lic_wiggy-brass-capuchin
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-rose-chimpanzee.sh
        container: qc.met_ugly-goldenrod-gorilla
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-jade-horse.sh
        container: qc.sec_gamy-flax-worm
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-purple-dachshund.sh
        container: qc.sty_stinky-olivine-mongrel
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-malachite-booby.sh
        container: qc.sty_droopy-linen-clam
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-taupe-caiman.sh
        container: qc.sty_sunny-russet-hare
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cinnabar-shrew.sh
        container: qc.uni_homely-ivory-kiwi
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-brown-weasel.sh
        container: qc.ver_woolly-yellow-serval
timeout: 5400
