config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1-1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-celadon-mole.sh
        container: qc.acc_cheeky-grey-hound
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-gamboge-termite.sh
        container: qc.doc_scummy-rust-spaniel
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-charcoal-raccoon.sh
        container: qc.doc_bluesy-wisteria-kangaroo
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-pink-fousek.sh
        container: qc.doc_gamy-gold-rattlesnake
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-carmine-javanese.sh
        container: qc.doc_skanky-black-capuchin
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-coral-quetzal.sh
        container: qc.lic_hazy-malachite-moorhen
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gamboge-chicken.sh
        container: qc.met_skanky-apricot-kingfisher
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cinnamon-sponge.sh
        container: qc.sec_snappy-mustard-crab
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-magenta-tuatara.sh
        container: qc.sty_snippy-indigo-tortoise
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-rust-bee.sh
        container: qc.sty_gummy-lime-tetra
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-orchid-woodlouse.sh
        container: qc.sty_stuffy-persimmon-paradise
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-brass-quail.sh
        container: qc.uni_shaggy-cerulean-macaque
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-fox.sh
        container: qc.ver_hazy-denim-fousek
timeout: 5400
