config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerise-fly.sh
        container: qc.acc_skinny-wheat-civet
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-emerald-shrimp.sh
        container: qc.doc_squeaky-bistre-dog
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-smalt-llama.sh
        container: qc.doc_greasy-buff-gorilla
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-tomato-dhole.sh
        container: qc.doc_cranky-chartreuse-cat
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-peach-hippopotamus.sh
        container: qc.doc_chewy-cyan-goose
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-green-butterfly.sh
        container: qc.lic_blurry-sapphire-capuchin
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-platinum-donkey.sh
        container: qc.met_nerdy-aqua-impala
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-teal-walrus.sh
        container: qc.sec_droopy-apricot-scorpion
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cinnamon-penguin.sh
        container: qc.sty_queasy-salmon-frigatebird
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ochre-eleuth.sh
        container: qc.sty_tasty-seashell-angelfish
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-tangerine-penguin.sh
        container: qc.sty_gummy-goldenrod-vulture
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-rose-chamois.sh
        container: qc.uni_tasty-eggplant-jaguar
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-firebrick-seahorse.sh
        container: qc.ver_chummy-myrtle-chamois
timeout: 5400
