config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: sqa
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cinnabar-vole.sh
        container: qc.acc_geeky-white-hyrax
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-coral-zebra.sh
        container: qc.doc_wheezy-platinum-panda
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-peach-elephant.sh
        container: qc.doc_nippy-xanthic-gopher
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-malachite-terrier.sh
        container: qc.doc_boozy-alizarin-worm
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-russet-squirrel.sh
        container: qc.doc_crappy-rose-kiwi
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cyan-ostrich.sh
        container: qc.lic_skimpy-cream-eel
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-yellow-octopus.sh
        container: qc.met_lumpy-teal-hornet
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rust-angelfish.sh
        container: qc.sec_cloudy-cerulean-ray
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-crimson-terrier.sh
        container: qc.sty_lanky-bronze-wrasse
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-blue-dollar.sh
        container: qc.sty_seedy-amethyst-wildebeest
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-brass-cheetah.sh
        container: qc.sty_flimsy-zucchini-forest
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-indigo-oyster.sh
        container: qc.uni_foggy-mauve-uguisu
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-razzmatazz-axolotl.sh
        container: qc.ver_pretty-viridian-echidna
timeout: 5400
