config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-magenta-starfish.sh
        container: qc.acc_nippy-black-woodlouse
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-sepia-spider.sh
        container: qc.doc_whiny-chocolate-ant
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-puce-barb.sh
        container: qc.doc_frumpy-buff-skunk
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-pumpkin-dugong.sh
        container: qc.doc_hilly-chocolate-goose
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-amethyst-dogfish.sh
        container: qc.doc_ready-saffron-squid
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-charcoal-dolphin.sh
        container: qc.lic_hasty-emerald-camel
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rust-russel.sh
        container: qc.met_frumpy-carmine-dolphin
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-smalt-barnacle.sh
        container: qc.sec_scummy-firebrick-quoll
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-xanthic-frise.sh
        container: qc.sty_sleepy-indigo-abyssinian
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-mustard-uguisu.sh
        container: qc.sty_goopy-green-argentino
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-flax-chicken.sh
        container: qc.sty_nerdy-mauve-falcon
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-fuchsia-opossum.sh
        container: qc.uni_surly-mauve-bison
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-blue-moose.sh
        container: qc.ver_gummy-bronze-leopard
timeout: 5400
