config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olivine-oriole.sh
        container: qc.acc_paltry-purple-hummingbird
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-red-clam.sh
        container: qc.doc_lanky-amaranth-raccoon
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cornflower-frog.sh
        container: qc.doc_boozy-tan-wildebeest
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-fuchsia-armadillo.sh
        container: qc.doc_lovely-ochre-chamois
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ruby-chow.sh
        container: qc.doc_bumpy-auburn-wallaby
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cerise-indri.sh
        container: qc.lic_cranky-turquoise-mayfly
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-yellow-sloth.sh
        container: qc.met_homely-cyan-millipede
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-green-monkey.sh
        container: qc.sec_bluesy-corn-seahorse
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-eggplant-beetle.sh
        container: qc.sty_gamy-lime-baboon
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-periwinkle-dodo.sh
        container: qc.sty_woozy-orange-mammoth
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-champagne-drever.sh
        container: qc.sty_leaky-turquoise-quokka
  QC.Uni:
    repos:
      github.com/grycap/im commands:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-plum-angelfish.sh
        container: qc.uni_pokey-pumpkin-dogfish
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-mustard-flamingo.sh
        container: qc.ver_stuffy-gamboge-russel
timeout: 5400
