config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-buff-ladybird.sh
        container: qc.acc_trippy-chartreuse-peccary
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-zucchini-toad.sh
        container: qc.doc_silly-alizarin-molly
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-xanthic-coyote.sh
        container: qc.doc_clammy-puce-squirt
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-sapphire-stingray.sh
        container: qc.doc_skimpy-wheat-quokka
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-pear-kakapo.sh
        container: qc.doc_droopy-tan-drever
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-champagne-grasshopper.sh
        container: qc.lic_lovely-bistre-hare
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-scarlet-capybara.sh
        container: qc.met_chummy-vermilion-dalmatian
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-black-barracuda.sh
        container: qc.sec_foggy-tangerine-urchin
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-jade-shark.sh
        container: qc.sty_crabby-rose-mongrel
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-mauve-bandicoot.sh
        container: qc.sty_stuffy-tomato-bear
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-pink-otter.sh
        container: qc.sty_stuffy-amber-rabbit
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-sangria-paradise.sh
        container: qc.uni_breezy-green-mayfly
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-white-angelfish.sh
        container: qc.ver_scummy-bistre-dane
timeout: 5400
