config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-teal-shrew.sh
        container: qc.acc_smelly-pear-starfish
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-eggplant-panda.sh
        container: qc.doc_sloppy-vermilion-cassowary
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-celadon-chimpanzee.sh
        container: qc.doc_breezy-chocolate-mongrel
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-grey-binturong.sh
        container: qc.doc_foggy-amethyst-gar
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-blue-russel.sh
        container: qc.doc_wiggy-sangria-magpie
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-blue-bear.sh
        container: qc.lic_ready-vermilion-tiger
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-linen-chameleon.sh
        container: qc.met_greasy-chestnut-tortoise
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cyan-worm.sh
        container: qc.sec_gummy-viridian-cow
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-grey-lionfish.sh
        container: qc.sty_craggy-eggplant-cassowary
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-ruby-macaque.sh
        container: qc.sty_cheeky-pink-gopher
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-dandelion-sloth.sh
        container: qc.sty_breezy-crimson-antelope
  QC.Uni:
    repos:
      github.com/grycap/im commands:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-asparagus-quoll.sh
        container: qc.uni_queasy-grey-cattle
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-auburn-monkey.sh
        container: qc.ver_freaky-peach-otter
timeout: 5400
