config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: sqa
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ecru-chicken.sh
        container: qc.acc_hazy-fuchsia-ladybird
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-peach-loon.sh
        container: qc.doc_nippy-amber-bombay
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-olive-urchin.sh
        container: qc.doc_silly-maroon-termite
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-mauve-tarantula.sh
        container: qc.doc_flabby-linen-hamster
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-harlequin-sponge.sh
        container: qc.doc_chewy-orange-gopher
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-malachite-wolf.sh
        container: qc.lic_cloudy-razzmatazz-discus
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lavender-coyote.sh
        container: qc.met_gummy-platinum-blue
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-brass-maltese.sh
        container: qc.sec_silly-lilac-duck
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-taupe-shrimp.sh
        container: qc.sty_sloppy-bronze-clam
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-teal-lynx.sh
        container: qc.sty_hazy-tangerine-tetra
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-copper-hound.sh
        container: qc.sty_lousy-chartreuse-yak
  QC.Uni:
    repos:
      github.com/grycap/im commands:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-white-moorhen.sh
        container: qc.uni_clammy-burgundy-labradoodle
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-khaki-magpie.sh
        container: qc.ver_cheeky-cornflower-zebra
timeout: 5400
