config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1-1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cerulean-havanese.sh
        container: qc.acc_foggy-pink-olm
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-vermilion-quoll.sh
        container: qc.doc_flaky-red-dormouse
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-lavender-tamarin.sh
        container: qc.doc_lanky-aquamarine-urchin
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-gamboge-monkey.sh
        container: qc.doc_whiny-crimson-koala
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-peach-boar.sh
        container: qc.doc_crabby-apricot-lobster
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-burgundy-worm.sh
        container: qc.lic_grumpy-sepia-shrew
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-blue-squirrel.sh
        container: qc.met_dorky-cyan-cuttlefish
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-sangria-sheepdog.sh
        container: qc.sec_tacky-heliotrope-crab
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-charcoal-malamute.sh
        container: qc.sty_baggy-goldenrod-hound
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-emerald-hyena.sh
        container: qc.sty_hazy-rose-hyena
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pink-bear.sh
        container: qc.sty_squirrely-champagne-newfoundland
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-aqua-ocelot.sh
        container: qc.uni_whiny-turquoise-earwig
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-coral-badger.sh
        container: qc.ver_shaky-viridian-quokka
timeout: 5400
