config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-champagne-wombat.sh
        container: qc.acc_paltry-corn-avocet
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-aquamarine-woodlouse.sh
        container: qc.doc_snoopy-gold-dolphin
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-yellow-chimpanzee.sh
        container: qc.doc_snippy-orchid-quetzal
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chocolate-wombat.sh
        container: qc.lic_paltry-cinnabar-wallaby
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-scarlet-urchin.sh
        container: qc.ver_hilly-denim-rattlesnake
timeout: 5400
