config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.19.2
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lime-earwig.sh
        container: qc.acc_flabby-maroon-robin
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-maroon-llama.sh
        container: qc.doc_baggy-sangria-bison
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-ivory-budgerigar.sh
        container: qc.doc_hasty-denim-hedgehog
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cornflower-saola.sh
        container: qc.doc_gloppy-sapphire-foxhound
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-taupe-molly.sh
        container: qc.doc_beady-rose-havanese
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pink-skunk.sh
        container: qc.lic_pasty-salmon-cheetah
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-alizarin-fox.sh
        container: qc.met_lanky-pumpkin-ant
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olivine-hyena.sh
        container: qc.sec_snoopy-cyan-peccary
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-pink-bobcat.sh
        container: qc.sty_gummy-cerise-kangaroo
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-charcoal-tuatara.sh
        container: qc.sty_lovely-olive-bongo
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bronze-echidna.sh
        container: qc.sty_gimpy-mustard-javanese
  QC.Uni:
    repos:
      github.com/grycap/im commands:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-dandelion-mongoose.sh
        container: qc.uni_tacky-beige-stingray
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-razzmatazz-ferret.sh
        container: qc.ver_dorky-khaki-tiger
timeout: 5400
