config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-brass-cassowary.sh
        container: qc.acc_squeaky-saffron-hummingbird
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-amber-harrier.sh
        container: qc.doc_homely-chocolate-dachshund
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-razzmatazz-chicken.sh
        container: qc.doc_snappy-red-dragonfly
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-denim-tortoise.sh
        container: qc.doc_queasy-sangria-paradise
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-tomato-otter.sh
        container: qc.doc_cranky-grey-bat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-russet-sloth.sh
        container: qc.lic_skinny-red-cheetah
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-wisteria-abyssinian.sh
        container: qc.met_pretty-pear-robin
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-buff-hedgehog.sh
        container: qc.sec_whiny-vermilion-scorpion
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-lilac-yak.sh
        container: qc.sty_sickly-harlequin-setter
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-denim-hedgehog.sh
        container: qc.sty_paltry-plum-goat
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-linen-cattle.sh
        container: qc.sty_ready-khaki-liger
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-lilac-mouse.sh
        container: qc.uni_ready-cinnamon-olm
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-harlequin-toad.sh
        container: qc.ver_flaky-olivine-axolotl
timeout: 5400
