config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-mouse.sh
        container: qc.acc_craggy-asparagus-retriever
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-asparagus-lionfish.sh
        container: qc.doc_nippy-brown-harrier
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-silver-vulture.sh
        container: qc.doc_sleazy-xanthic-moose
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-pink-coral.sh
        container: qc.doc_dorky-xanthic-chamois
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-flax-harrier.sh
        container: qc.doc_muzzy-green-wrasse
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-olivine-lion.sh
        container: qc.lic_squirrely-cream-retriever
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-russet-bloodhound.sh
        container: qc.met_randy-ultramarine-tarsier
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cobalt-chin.sh
        container: qc.sec_tasty-sangria-eleuth
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-sangria-retriever.sh
        container: qc.sty_cozy-smalt-bonobo
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-buff-ladybird.sh
        container: qc.sty_tacky-ultramarine-anteater
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-russet-sponge.sh
        container: qc.sty_muggy-magenta-russel
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-silver-flounder.sh
        container: qc.uni_gamy-olive-greyhound
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-bronze-hound.sh
        container: qc.ver_crappy-viridian-buzzard
timeout: 5400
