config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cobalt-cat.sh
        container: qc.acc_sickly-russet-spitz
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-alizarin-tamarin.sh
        container: qc.doc_gamy-fuchsia-magpie
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-tomato-grasshopper.sh
        container: qc.doc_skinny-olive-capuchin
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-malachite-robin.sh
        container: qc.doc_baggy-khaki-newt
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-apricot-uakari.sh
        container: qc.doc_ready-jade-bee
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cerulean-pinscher.sh
        container: qc.lic_muzzy-amaranth-tetra
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cerulean-argentino.sh
        container: qc.met_homey-bistre-cuttlefish
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-carmine-macaque.sh
        container: qc.sec_lanky-tomato-bee
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-pink-neanderthal.sh
        container: qc.sty_gamy-amber-echidna
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-malachite-grasshopper.sh
        container: qc.sty_boozy-orange-millipede
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-pumpkin-scorpion.sh
        container: qc.sty_skimpy-goldenrod-newt
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-myrtle-affenpinscher.sh
        container: qc.ver_chewy-buff-chinook
timeout: 5400
