config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mauve-cuscus.sh
        container: qc.acc_messy-denim-whippet
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-plum-bird.sh
        container: qc.doc_craggy-jade-crocodile
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pear-capuchin.sh
        container: qc.doc_snippy-aquamarine-mongrel
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-linen-husky.sh
        container: qc.lic_pasty-orchid-catfish
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-amber-alligator.sh
        container: qc.ver_snoopy-taupe-coati
timeout: 5400
