config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1-1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-champagne-reindeer.sh
        container: qc.acc_sickly-ruby-bird
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-orange-moose.sh
        container: qc.doc_squirrely-aqua-raccoon
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ivory-kangaroo.sh
        container: qc.doc_smelly-olivine-dodo
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-linen-sheep.sh
        container: qc.doc_blurry-purple-ostrich
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cyan-quokka.sh
        container: qc.doc_scanty-cardinal-giraffe
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-linen-angelfish.sh
        container: qc.lic_ready-crimson-squirt
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-smalt-dunker.sh
        container: qc.met_shabby-chartreuse-coyote
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-crimson-mouse.sh
        container: qc.sec_droopy-indigo-hummingbird
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-magnolia-coral.sh
        container: qc.sty_sloppy-flax-ostrich
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-purple-fly.sh
        container: qc.sty_grumpy-heliotrope-zebra
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-crimson-hippopotamus.sh
        container: qc.sty_ugly-carmine-mayfly
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ecru-birman.sh
        container: qc.uni_tasty-cerise-zebra
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-gamboge-vole.sh
        container: qc.ver_silly-gold-liger
timeout: 5400
