config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.daffodil_productive_panda.sh
        container: qc.acc_lemon_ardent_toad
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.taupe_reflective_vulture.sh
        container: qc.doc_green_generous_axolotl
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.cornflower_analytical_unicorn.sh
        container: qc.doc_sienna_skeptical_turtle
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.yellow_gentle_gerbil.sh
        container: qc.doc_paprika_calm_emu
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pink_analytical_lionfish.sh
        container: qc.doc_khaki_meticulous_emu
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.rust_timid_toad.sh
        container: qc.lic_cloud_gracious_ostrich
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ochre_inventive_dolphin.sh
        container: qc.met_ebony_stoic_pangolin
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.white_funny_octopus.sh
        container: qc.sec_wave_artistic_emu
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slate_blissful_sloth.sh
        container: qc.sty_strawberry_reflective_axolotl
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cobalt_empathetic_jellyfish.sh
        container: qc.sty_emerald_grateful_camel
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.iris_organized_reindeer.sh
        container: qc.sty_fuchsia_clever_serval
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.viridian_protective_cassowary.sh
        container: qc.uni_lime_friendly_capybara
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.mango_worried_bear.sh
        container: qc.ver_poppy_outgoing_ferret
timeout: 5400
