config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-flax-macaw.sh
        container: qc.acc_droopy-persimmon-chipmunk
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-myrtle-hyena.sh
        container: qc.doc_zippy-wisteria-tang
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amber-hyena.sh
        container: qc.doc_boozy-apricot-guppy
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-brass-gar.sh
        container: qc.doc_homely-beige-impala
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-razzmatazz-wrasse.sh
        container: qc.doc_craggy-chocolate-bat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-seashell-tortoise.sh
        container: qc.lic_chummy-apricot-discus
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-heliotrope-bobcat.sh
        container: qc.met_jumpy-alizarin-kingfisher
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-silver-giraffe.sh
        container: qc.sec_gummy-malachite-zonkey
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cobalt-fowl.sh
        container: qc.sty_wheezy-saffron-loon
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cardinal-hound.sh
        container: qc.sty_flimsy-alizarin-scorpion
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-xanthic-macaw.sh
        container: qc.sty_wheezy-gamboge-drever
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-tan-mule.sh
        container: qc.uni_droopy-auburn-alligator
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-chartreuse-foxhound.sh
        container: qc.ver_snazzy-cobalt-tarsier
timeout: 5400
