config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    www:
      branch: master
      repo: https://www.github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      www git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-blue-opossum.sh
        container: qc.acc_beady-cerulean-mastiff
  QC.Doc:
    repos:
      www find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-russet-cichlid.sh
        container: qc.doc_scanty-platinum-armadillo
      www git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-sangria-dingo.sh
        container: qc.doc_skimpy-cinnamon-hornet
      www markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-azure-dunker.sh
        container: qc.doc_squeaky-bistre-jackal
      www restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-copper-bobcat.sh
        container: qc.doc_flabby-pear-ocelot
  QC.Lic:
    repos:
      www licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sangria-deer.sh
        container: qc.lic_pretty-carmine-slug
  QC.Met:
    repos:
      www validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-corn-cichlid.sh
        container: qc.met_squirrely-turquoise-squirrel
  QC.Sec:
    repos:
      www bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-platinum-wolverine.sh
        container: qc.sec_blurry-rose-fousek
  QC.Sty:
    repos:
      www flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lavender-wasp.sh
        container: qc.sty_ugly-persimmon-dogfish
      www hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ochre-dragon.sh
        container: qc.sty_wheezy-lilac-kakapo
      www jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-celadon-anteater.sh
        container: qc.sty_pokey-dandelion-shark
  QC.Uni:
    repos:
      www pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-vermilion-foxhound.sh
        container: qc.uni_randy-red-ant
  QC.Ver:
    repos:
      www get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-chestnut-budgerigar.sh
        container: qc.ver_droopy-violet-mongrel
timeout: 5400
