config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-myrtle-burmese.sh
        container: qc.acc_sleepy-yellow-grouse
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cornflower-shrew.sh
        container: qc.doc_lousy-lemon-axolotl
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-slug.sh
        container: qc.doc_lovely-harlequin-baboon
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pink-camel.sh
        container: qc.doc_paltry-bronze-dollar
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-bistre-guppy.sh
        container: qc.doc_skimpy-charcoal-argentino
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cyan-blue.sh
        container: qc.lic_nippy-cornflower-reindeer
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-pear-wolfhound.sh
        container: qc.met_snippy-tomato-javanese
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-grey-dunker.sh
        container: qc.sec_tacky-myrtle-dragon
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-viridian-dragonfly.sh
        container: qc.sty_muggy-firebrick-oyster
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cinnamon-orangutan.sh
        container: qc.sty_baggy-mauve-schnauzer
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-maroon-mau.sh
        container: qc.sty_lousy-pink-coyote
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-fuchsia-markhor.sh
        container: qc.uni_muggy-gamboge-gecko
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-buff-akbash.sh
        container: qc.ver_cozy-beige-collie
timeout: 5400
