config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: sqa
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-peach-angora.sh
        container: qc.acc_chummy-mustard-manatee
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-amber-duck.sh
        container: qc.doc_skanky-magenta-rottweiler
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-vermilion-kiwi.sh
        container: qc.doc_surly-apricot-audemer
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-chocolate-tamarin.sh
        container: qc.doc_bluesy-viridian-cassowary
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-bronze-wrasse.sh
        container: qc.doc_stinky-mauve-bear
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-plum-lynx.sh
        container: qc.lic_homey-cobalt-fossa
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olivine-shark.sh
        container: qc.met_scanty-viridian-eel
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-plum-retriever.sh
        container: qc.sec_muggy-lemon-crocodile
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ultramarine-bandicoot.sh
        container: qc.sty_gamy-plum-caracal
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-heliotrope-beagle.sh
        container: qc.sty_chummy-harlequin-chinchilla
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cobalt-avocet.sh
        container: qc.sty_tasty-saffron-crocodile
  QC.Uni:
    repos:
      github.com/grycap/im commands:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cardinal-boar.sh
        container: qc.uni_messy-burgundy-vole
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-yellow-elephant.sh
        container: qc.ver_bumpy-jade-neanderthal
timeout: 5400
