config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-vermilion-echidna.sh
        container: qc.acc_droopy-tangerine-russel
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-viridian-caterpillar.sh
        container: qc.doc_wimpy-indigo-ibis
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lavender-goose.sh
        container: qc.doc_muggy-rust-worm
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-beige-panda.sh
        container: qc.doc_smelly-flax-turkey
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lemon-beetle.sh
        container: qc.doc_grumpy-gold-fox
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-mauve-dragon.sh
        container: qc.lic_wheezy-cream-dunker
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-buff-whale.sh
        container: qc.met_skanky-auburn-meerkat
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-seashell-bloodhound.sh
        container: qc.sec_gummy-ochre-rat
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-crimson-cattle.sh
        container: qc.sty_pasty-charcoal-moose
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-aqua-boar.sh
        container: qc.sty_tasty-malachite-maltese
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-corn-frog.sh
        container: qc.sty_droopy-heliotrope-skunk
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-olive-russel.sh
        container: qc.uni_messy-mustard-camel
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-ivory-iguana.sh
        container: qc.ver_leaky-gamboge-mule
timeout: 5400
