config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.0
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-rose-husky.sh
        container: qc.acc_baggy-sepia-rabbit
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sepia-falcon.sh
        container: qc.doc_tasty-buff-spoonbill
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-olivine-magpie.sh
        container: qc.doc_bumpy-linen-opossum
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cyan-bee.sh
        container: qc.doc_fuzzy-sepia-squid
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-alizarin-chamois.sh
        container: qc.doc_skinny-cerulean-whale
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ivory-tortoise.sh
        container: qc.lic_tasty-turquoise-affenpinscher
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-brown-chimpanzee.sh
        container: qc.met_lovely-ultramarine-gerbil
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-lavender-spoonbill.sh
        container: qc.sec_skanky-coral-olm
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-periwinkle-grouse.sh
        container: qc.sty_muggy-vermilion-hamster
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-brown-elephant.sh
        container: qc.sty_gummy-harlequin-audemer
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-celadon-squirrel.sh
        container: qc.sty_flimsy-goldenrod-impala
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-buff-rattlesnake.sh
        container: qc.uni_queasy-malachite-sheep
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-lilac-bracke.sh
        container: qc.ver_randy-wisteria-goat
timeout: 5400
