config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-bistre-spider.sh
        container: qc.acc_hilly-buff-squid
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-seashell-beaver.sh
        container: qc.doc_crabby-malachite-guppy
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-orchid-mouse.sh
        container: qc.doc_sickly-orange-abyssinian
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cerise-gecko.sh
        container: qc.doc_skanky-copper-goose
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-vermilion-sponge.sh
        container: qc.doc_sloppy-aqua-eagle
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sapphire-bandicoot.sh
        container: qc.lic_craggy-celadon-woodlouse
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-malachite-caterpillar.sh
        container: qc.met_frumpy-olive-chinchilla
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-smalt-vole.sh
        container: qc.sec_trippy-lemon-penguin
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-crimson-forest.sh
        container: qc.sty_baggy-cyan-foxhound
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-khaki-millipede.sh
        container: qc.sty_randy-jade-bear
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-peach-mouse.sh
        container: qc.sty_shaky-white-fowl
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-saffron-fowl.sh
        container: qc.uni_frumpy-lemon-schnauzer
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-alizarin-wrasse.sh
        container: qc.ver_ready-white-swan
timeout: 5400
