config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cinnamon-chin.sh
        container: qc.acc_homey-amber-rottweiler
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-tomato-owl.sh
        container: qc.doc_cloudy-blue-burmese
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-heliotrope-mule.sh
        container: qc.doc_stuffy-jade-molly
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-eggplant-yak.sh
        container: qc.doc_gummy-apricot-magpie
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cyan-angelfish.sh
        container: qc.doc_foggy-charcoal-wombat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-black-skunk.sh
        container: qc.lic_sleazy-wheat-sponge
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-rose-echidna.sh
        container: qc.met_randy-alizarin-spaniel
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-blue-kangaroo.sh
        container: qc.sec_shabby-zucchini-termite
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-magnolia-deer.sh
        container: qc.sty_zippy-turquoise-gecko
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chestnut-spider.sh
        container: qc.sty_jumpy-persimmon-chinook
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-magnolia-boar.sh
        container: qc.sty_gummy-violet-schnauzer
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-fossa.sh
        container: qc.uni_tacky-firebrick-bear
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-olivine-cockroach.sh
        container: qc.ver_craggy-linen-whale
timeout: 5400
