config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: v1.17.1-1
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ivory-leopard.sh
        container: qc.acc_smelly-olive-robin
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-brass-buzzard.sh
        container: qc.doc_goopy-scarlet-fox
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-linen-lynx.sh
        container: qc.doc_sloppy-persimmon-llama
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cinnamon-quail.sh
        container: qc.doc_cloudy-cardinal-foxhound
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-charcoal-dormouse.sh
        container: qc.doc_shaky-cornflower-affenpinscher
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olive-turkey.sh
        container: qc.lic_stuffy-cardinal-owl
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homely-razzmatazz-camel.sh
        container: qc.met_flimsy-pink-collie
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-smalt-chipmunk.sh
        container: qc.sec_snazzy-charcoal-anteater
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-copper-axolotl.sh
        container: qc.sty_lovely-lime-barracuda
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-white-mongoose.sh
        container: qc.sty_craggy-chestnut-guppy
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-heliotrope-chameleon.sh
        container: qc.sty_baggy-corn-crab
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cobalt-bandicoot.sh
        container: qc.uni_snazzy-sapphire-squirrel
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-olivine-opossum.sh
        container: qc.ver_nerdy-smalt-heron
timeout: 5400
