config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: sqa
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-wisteria-cheetah.sh
        container: qc.acc_cozy-white-goat
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-carmine-snake.sh
        container: qc.doc_baggy-celadon-chinchilla
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-scarlet-lion.sh
        container: qc.doc_homey-chestnut-hornet
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-chimpanzee.sh
        container: qc.doc_frumpy-maroon-seal
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cerise-snail.sh
        container: qc.doc_seedy-red-ibis
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-green-tuatara.sh
        container: qc.lic_hasty-orchid-nightingale
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chocolate-devil.sh
        container: qc.met_bumpy-white-quetzal
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sapphire-bandicoot.sh
        container: qc.sec_sickly-lilac-baboon
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cream-molly.sh
        container: qc.sty_jumpy-smalt-russel
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-emerald-goose.sh
        container: qc.sty_chummy-platinum-stoat
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cinnamon-gharial.sh
        container: qc.sty_snoopy-orange-frigatebird
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sangria-salamander.sh
        container: qc.uni_bumpy-zucchini-squirrel
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-aquamarine-kingfisher.sh
        container: qc.ver_sloppy-thistle-insect
timeout: 5400
