config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lavender-cockroach.sh
        container: qc.acc_goopy-yellow-ray
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-orange-ant.sh
        container: qc.doc_muzzy-periwinkle-mandrill
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-gold-lizard.sh
        container: qc.doc_scaly-gamboge-sponge
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-green-cockroach.sh
        container: qc.doc_muggy-sepia-blue
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-black-tuatara.sh
        container: qc.doc_gloppy-pear-beagle
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cardinal-gopher.sh
        container: qc.lic_crappy-buff-zorse
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-jade-dragon.sh
        container: qc.met_messy-platinum-jellyfish
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-asparagus-wallaby.sh
        container: qc.sec_randy-wisteria-crane
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-taupe-kakapo.sh
        container: qc.sty_fuzzy-gold-harrier
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-vermilion-tetra.sh
        container: qc.sty_leaky-black-gecko
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-bistre-flounder.sh
        container: qc.sty_sleazy-lime-tuatara
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-scarlet-wolf.sh
        container: qc.uni_beady-auburn-argentino
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-platinum-snake.sh
        container: qc.ver_stuffy-amber-forest
timeout: 5400
